server:
  port: 8080

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: 123456
    # 在考虑结束之前等待的时间
    close-timeout: 15s
    # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    in-memory: true
    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
    # 等待消息发送响应的时间。设置为0等待永远。
    send-timeout: 0
    queue-name: active.queue
    topic-name: active.topic.name.model

  #  packages:
  #    trust-all: true #不配置此项，会报错
  pool:
    enabled: true
    #连接池最大连接数
    max-connections: 10
    #空闲的连接过期时间，默认为30秒
    idle-timeout: 30000

  jms:
    #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
    pub-sub-domain: true
